---
- name: Example Playbook with Register
  hosts: webserver
  tasks:
    - name: Get system uptime
      command: uptime
      register: uptime_result

    - name: Display uptime
      debug:
        msg: "{{ uptime_result.rc }}"
        
