---
- name: Example Playbook with Register
  hosts: webserver
  become: yes
  tasks:
    - name: install required softwares
      package:
        name: "{{ item }}"
        state: absent
      loop:
        - httpd
        - ntp
        - wget
        - telnet
      register: softare_installation_output
    - name: show softare_installation_output
      debug:
        msg: "{{ softare_installation_output }}"
