---
- name: Example Playbook with Register
  hosts: webserver
  become: yes
  tasks:
    - name: install required softwares
      package:
        name: "{{ item }}"
        state: present
      loop:
        - httpd
        - ntp
        - wget
        - telnet
      loop_control:
        pause: 5
      register: softare_installation_output

    - name: show softare_installation_output
      debug:
        msg: "item position is : {{ idx }} , {{ software.results }}"
      loop: "{{ softare_installation_output.results }}"
      loop_control:
        loop_var: software
        label: "{{ inventory_hostname }}"
        index_var: idx
        pause: 10
